### ISSUE TITLE
I can't download or send to server when I use in my local pc.

### ISSUE THREAD

**Issue by wasim47** [mattar88/imageMaker#1]
The problem is here

Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at HTMLAnchorElement.<anonymous> (file:///C:/Users/Mohammad%20Wasim/Desktop/imagemaker/imageMaker.min.js:1:23718)
    at HTMLAnchorElement.dispatch (https://code.jquery.com/jquery-3.6.0.min.js:2:43064)
    at HTMLAnchorElement.v.handle (https://code.jquery.com/jquery-3.6.0.min.js:2:41048)

Please sir help me

**Comment by mattar88** [comment]
Hello Dear,
 
I think you should load your files from the local server (localhost request http:// ) instead of loading them from the local file system( c:/ or file://...).

Hope this helps
